name: Penetration Testing Workflow

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL for penetration testing'
        required: true

jobs:
  nmap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nmap
        run: sudo apt-get install -y nmap

      - name: Run Nmap Scan
        run: nmap -sV -oN nmap_scan_results.txt ${{ github.event.inputs.target_url }}

      - name: Display Nmap Results
        run: cat nmap_scan_results.txt

  zap_scan:
    runs-on: ubuntu-latest
    needs: nmap_scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
          tar -xvzf ZAP_2.11.1_Linux.tar.gz
          sudo mv ZAP_2.11.1 /opt/zap

      - name: Run OWASP ZAP Baseline Scan
        run: |
          /opt/zap/zap.sh -cmd -quickurl ${{ github.event.inputs.target_url }} -quickprogress -quickout zap_scan_results.txt

      - name: Display OWASP ZAP Results
        run: cat zap_scan_results.txt
