name: Jok3r Bug Bounty Attack

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL for testing'
        required: true

jobs:
  jok3r_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv git
          sudo apt-get install -y nmap sqlmap nikto whatweb gobuster wfuzz

      - name: Install Jok3r
        run: |
          git clone https://github.com/koutto/jok3r.git
          cd jok3r
          pip3 install -r requirements.txt
          sudo ln -sf "$PWD/jok3r.py" /usr/local/bin/jok3r
          echo "$PWD" >> $GITHUB_PATH

      - name: Verify Jok3r Installation
        run: |
          which jok3r || echo "Jok3r not found"
          sudo jok3r --version || echo "Jok3r version check failed"

      - name: Run Jok3r Attack
        run: |
          sudo jok3r attack -t ${{ github.event.inputs.target_url }} --output jok3r_results || echo "Jok3r attack failed"

      - name: Display Jok3r Results
        run: cat jok3r_results/* || echo "No Jok3r results found"
