name: Run LinkFinder on URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to scan with LinkFinder'
        required: true
        type: string

jobs:
  run-linkfinder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/GerbenJavado/LinkFinder.git
          cd LinkFinder
          python setup.py install
          pip install -r requirements.txt

      - name: Create output directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/output

      - name: Run LinkFinder and save output to file
        run: |
          cd LinkFinder
          python linkfinder.py -i ${{ github.event.inputs.url }} -o cli > $GITHUB_WORKSPACE/output/results.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: linkfinder-results
          path: $GITHUB_WORKSPACE/output/results.txt
