name: Jok3r Security Scan

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'Comma-separated list of URLs to scan'
        required: true

jobs:
  jok3r_scan:
    runs-on: ubuntu-latest
    # GitHub Actions runners come with 7 GB of memory, so we should keep memory usage under control

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev git curl ca-certificates

      - name: Stop all running Docker containers (to free resources)
        run: |
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker rm $(sudo docker ps -a -q) || true

      - name: Pull Jok3r Docker Image
        run: |
          sudo docker pull koutto/jok3r

      - name: Start Jok3r container with memory limits
        run: |
          # Run the Jok3r container with limited memory and CPU to prevent overuse of system resources
          sudo docker run -d \
            --name jok3r-container \
            --memory="2g" \ # Limit memory to 2GB (adjust as necessary for your setup)
            --cpus="1.0" \ # Limit CPU to 1 core (adjust as necessary)
            koutto/jok3r python3 jok3r.py --help

      - name: Clone Jok3r and Install Dependencies in Docker Container
        run: |
          # Use the 'docker exec' command carefully to avoid overloading memory
          sudo docker exec jok3r-container python3 jok3r.py toolbox --install-all --fast

      - name: Run Jok3r Scan on Provided URLs
        run: |
          # Read URLs and loop through them with proper memory usage in mind
          IFS=',' read -r -a urls <<< "${{ github.event.inputs.urls }}"
          for url in "${urls[@]}"; do
            echo "Scanning $url"
            # Limiting the number of concurrent scans to prevent excessive resource usage
            sudo docker exec jok3r-container python3 jok3r.py attack -t "$url" --all
            sleep 5 # Adding a short delay between scans to reduce CPU strain
          done

      - name: Cleanup Docker container
        run: |
          # Properly stopping and removing the Docker container to free up resources
          sudo docker stop jok3r-container
          sudo docker rm jok3r-container

