name: Jok3r Security Scan

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'Comma-separated list of URLs to scan'
        required: true
        default: 'http://example1.com,http://example2.com'

jobs:
  jok3r_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install docker
          sudo docker pull koutto/jok3r
          sudo docker run -i -t --name jok3r-container -w /root/jok3r --net=host koutto/jok3r

      - name: Clone Jok3r and Install
        run: |
          python3 jok3r.py toolbox --install-all --fast

      - name: Run Jok3r Scan on Provided URLs
        run: |
          IFS=',' read -r -a urls <<< "${{ github.event.inputs.urls }}"
          for url in "${urls[@]}"; do
            echo "Scanning $url"
            python3 jok3r.py attack -t "$url" --all
          done
