name: Recon Scan

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain to scan'
        required: true

env:
  GO_VERSION: '1.22'

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ github.event.inputs.domain }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ParamSpider
        run: |
          git clone https://github.com/devanshbatham/ParamSpider paramspider
          cd paramspider
          pip install .        # :contentReference[oaicite:8]{index=8}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}    # :contentReference[oaicite:9]{index=9}

      - name: Install Nuclei
        run: |
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest  # :contentReference[oaicite:10]{index=10}

      - name: Update Nuclei Templates
        run: |
          nuclei -update-templates   # :contentReference[oaicite:11]{index=11}

      - name: Run ParamSpider
        run: |
          paramspider -d $DOMAIN -o params.txt   # :contentReference[oaicite:12]{index=12}

      - name: Run Nuclei Scan
        run: |
          nuclei -l params.txt -o nuclei_results.txt   # :contentReference[oaicite:13]{index=13}

      - name: Upload ParamSpider Results
        uses: actions/upload-artifact@v3
        with:
          name: paramspider-urls
          path: params.txt

      - name: Upload Nuclei Findings
        uses: actions/upload-artifact@v3
        with:
          name: nuclei-findings
          path: nuclei_results.txt
