name: Jok3r Security Scan

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'Comma-separated list of URLs to scan'
        required: true
        
jobs:
  jok3r_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo docker pull koutto/jok3r
          sudo docker run -i -t --name jok3r-container -w /root/jok3r --net=host koutto/jok3r
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: Clone Jok3r and Install
        run: |
          python3 jok3r.py toolbox --install-all --fast

      - name: Run Jok3r Scan on Provided URLs
        run: |
          IFS=',' read -r -a urls <<< "${{ github.event.inputs.urls }}"
          for url in "${urls[@]}"; do
            echo "Scanning $url"
            python3 jok3r.py attack -t "$url" --all
          done
